import type { XPost, XProfile } from '@/types/x';

export type MockPost = {
  id: string;
  text: string;
  createdAt: string;
  likes: number;
  reposts: number;
  replies: number;
  views: number;
  media?: string;
  hashtags: string[];
  mentions: string[];
};

export const MOCK_PROFILE: XProfile = {
  id: 'u_hitx_demo',
  name: 'Avery Chen',
  username: 'averybuilds',
  description: 'Product engineer sharing experiments on AI UX and frontend architecture.',
  profileImageUrl: 'https://picsum.photos/seed/hitx-profile/120/120',
};

export const MOCK_FLAGS = {
  // Toggle this to true to validate the error state in the UI prototype.
  simulateError: false,
  // Toggle this to true to validate an authenticated-but-empty timeline.
  simulateEmpty: false,
  authDelayRangeMs: [1000, 1800] as const,
  fetchDelayRangeMs: [550, 780] as const,
};

export const MOCK_POSTS: MockPost[] = [
  {
    id: 'p001',
    text: 'Shipped a tiny improvement: keyboard shortcuts for every modal in our dashboard. Small UX wins compound fast.',
    createdAt: '2026-02-15T09:12:00.000Z',
    likes: 482,
    reposts: 76,
    replies: 23,
    views: 12440,
    hashtags: ['frontend', 'ux'],
    mentions: ['reactjs', 'tailwindcss'],
  },
  {
    id: 'p002',
    text: 'We replaced three loading spinners with skeletons and saw a measurable drop in bounce. Perceived speed matters.',
    createdAt: '2026-02-14T18:32:00.000Z',
    likes: 1092,
    reposts: 211,
    replies: 48,
    views: 31990,
    media: 'https://picsum.photos/seed/hitx-2/1200/720',
    hashtags: ['performance', 'design'],
    mentions: ['nextjs'],
  },
  {
    id: 'p003',
    text: 'If your components do too much, split by responsibility, not file size. Behavior first, visuals second.',
    createdAt: '2026-02-13T13:09:00.000Z',
    likes: 612,
    reposts: 98,
    replies: 37,
    views: 18400,
    hashtags: ['cleanarchitecture', 'typescript'],
    mentions: ['vercel'],
  },
  {
    id: 'p004',
    text: 'Today in profiling: one unstable callback forced 200 cards to repaint. Memoization is not optional at scale.',
    createdAt: '2026-02-12T08:01:00.000Z',
    likes: 845,
    reposts: 132,
    replies: 29,
    views: 24300,
    hashtags: ['react', 'webperf'],
    mentions: ['chromeDevTools'],
  },
  {
    id: 'p005',
    text: 'A good search box is a product feature, not a field. Debounce, highlight, and meaningful empty states.',
    createdAt: '2026-02-11T20:24:00.000Z',
    likes: 730,
    reposts: 142,
    replies: 19,
    views: 21090,
    hashtags: ['search', 'product'],
    mentions: ['elastic'],
  },
  {
    id: 'p006',
    text: 'Swapping card borders from static gray to theme tokens gave us instant dark mode parity across the app.',
    createdAt: '2026-02-11T11:53:00.000Z',
    likes: 401,
    reposts: 51,
    replies: 12,
    views: 10202,
    hashtags: ['theming', 'tailwind'],
    mentions: ['shadcn'],
  },
  {
    id: 'p007',
    text: 'The best onboarding copy we wrote this week: one sentence, one action, one outcome.',
    createdAt: '2026-02-10T16:17:00.000Z',
    likes: 955,
    reposts: 168,
    replies: 56,
    views: 28014,
    media: 'https://picsum.photos/seed/hitx-7/1000/640',
    hashtags: ['copywriting', 'saas'],
    mentions: ['figma'],
  },
  {
    id: 'p008',
    text: 'Hot take: prototypes should include edge-state polish, otherwise you are not testing real UX quality.',
    createdAt: '2026-02-10T10:40:00.000Z',
    likes: 1331,
    reposts: 271,
    replies: 78,
    views: 40111,
    hashtags: ['prototype', 'uxresearch'],
    mentions: ['producthunt'],
  },
  {
    id: 'p009',
    text: 'Deployed a masonry-like feed with CSS columns for variable-height content. No JS layout library needed.',
    createdAt: '2026-02-09T21:02:00.000Z',
    likes: 589,
    reposts: 93,
    replies: 17,
    views: 16100,
    hashtags: ['css', 'masonry'],
    mentions: ['mdnwebdocs'],
  },
  {
    id: 'p010',
    text: 'What makes a premium interface? Tight spacing rhythm, visual restraint, and fast interactions.',
    createdAt: '2026-02-09T07:15:00.000Z',
    likes: 1210,
    reposts: 219,
    replies: 64,
    views: 36850,
    hashtags: ['ui', 'designsystems'],
    mentions: ['apple'],
  },
  {
    id: 'p011',
    text: 'Refactored API adapters to return domain models only. UI no longer knows provider payload shapes.',
    createdAt: '2026-02-08T18:48:00.000Z',
    likes: 463,
    reposts: 67,
    replies: 14,
    views: 12890,
    hashtags: ['architecture', 'api'],
    mentions: ['graphql'],
  },
  {
    id: 'p012',
    text: 'A11y check: every icon-only control now has a meaningful label. Keyboard-only flow feels much better.',
    createdAt: '2026-02-08T09:27:00.000Z',
    likes: 672,
    reposts: 108,
    replies: 21,
    views: 18670,
    hashtags: ['accessibility', 'frontend'],
    mentions: ['w3c'],
  },
  {
    id: 'p013',
    text: 'Preview from our new analytics bar: total posts, likes, and median views in one glance.',
    createdAt: '2026-02-07T22:30:00.000Z',
    likes: 514,
    reposts: 83,
    replies: 10,
    views: 15231,
    media: 'https://picsum.photos/seed/hitx-13/1280/720',
    hashtags: ['analytics', 'dashboard'],
    mentions: ['datadog'],
  },
  {
    id: 'p014',
    text: 'When search query is empty, showing everything is fine, but you should still communicate what is happening.',
    createdAt: '2026-02-07T14:05:00.000Z',
    likes: 377,
    reposts: 45,
    replies: 8,
    views: 9730,
    hashtags: ['searchux', 'productdesign'],
    mentions: ['notionhq'],
  },
  {
    id: 'p015',
    text: 'Added a compact list mode for power users. It is surprisingly effective for scanning 100+ posts quickly.',
    createdAt: '2026-02-06T17:58:00.000Z',
    likes: 883,
    reposts: 154,
    replies: 33,
    views: 26234,
    hashtags: ['ux', 'powerusers'],
    mentions: ['linear'],
  },
  {
    id: 'p016',
    text: 'Shipping note: keeping prototype and production contracts aligned saves painful rewrites later.',
    createdAt: '2026-02-06T08:11:00.000Z',
    likes: 358,
    reposts: 41,
    replies: 6,
    views: 8604,
    hashtags: ['engineering', 'prototype'],
    mentions: ['github'],
  },
  {
    id: 'p017',
    text: 'Search supports mentions too. Try querying @nextjs or @reactjs and watch highlights update live.',
    createdAt: '2026-02-05T20:03:00.000Z',
    likes: 701,
    reposts: 122,
    replies: 24,
    views: 19914,
    hashtags: ['search', 'dx'],
    mentions: ['nextjs', 'reactjs'],
  },
  {
    id: 'p018',
    text: 'User interview quote: "I can finally find that thread from last year in seconds." That is the bar.',
    createdAt: '2026-02-05T11:39:00.000Z',
    likes: 1175,
    reposts: 246,
    replies: 75,
    views: 38901,
    hashtags: ['research', 'userfeedback'],
    mentions: ['x'],
  },
  {
    id: 'p019',
    text: 'Implemented optimistic theme transitions with no flash between SSR and hydration.',
    createdAt: '2026-02-04T16:13:00.000Z',
    likes: 489,
    reposts: 79,
    replies: 16,
    views: 14022,
    hashtags: ['nextjs', 'themes'],
    mentions: ['nextthemes'],
  },
  {
    id: 'p020',
    text: 'Tiny detail: metric chips now have consistent min-width, so card footers align cleanly across breakpoints.',
    createdAt: '2026-02-04T09:55:00.000Z',
    likes: 312,
    reposts: 34,
    replies: 4,
    views: 7418,
    hashtags: ['ui', 'polish'],
    mentions: ['tailwindcss'],
  },
  {
    id: 'p021',
    text: 'Using only CSS animations for card entrance keeps the prototype lightweight and dependency-free.',
    createdAt: '2026-02-03T22:42:00.000Z',
    likes: 530,
    reposts: 73,
    replies: 11,
    views: 15349,
    hashtags: ['css', 'animation'],
    mentions: ['webdev'],
  },
  {
    id: 'p022',
    text: 'Switched search matching to include hashtag and mention indexes. Accuracy improved immediately.',
    createdAt: '2026-02-03T13:21:00.000Z',
    likes: 648,
    reposts: 99,
    replies: 18,
    views: 17782,
    hashtags: ['search', 'indexing'],
    mentions: ['algolia'],
  },
  {
    id: 'p023',
    text: 'Weekly recap: 4 UX experiments, 2 rollouts, 0 regressions. Slow is smooth, smooth is fast.',
    createdAt: '2026-02-02T18:06:00.000Z',
    likes: 925,
    reposts: 180,
    replies: 28,
    views: 29671,
    media: 'https://picsum.photos/seed/hitx-23/1100/700',
    hashtags: ['buildinpublic', 'product'],
    mentions: ['vercel'],
  },
  {
    id: 'p024',
    text: 'Design review ritual: remove one visual element from every screen. If clarity improves, keep it removed.',
    createdAt: '2026-02-02T09:44:00.000Z',
    likes: 793,
    reposts: 139,
    replies: 31,
    views: 22164,
    hashtags: ['minimalism', 'uidesign'],
    mentions: ['figma'],
  },
];

export const mapMockPostToXPost = (post: MockPost): XPost => ({
  id: post.id,
  text: post.text,
  createdAt: post.createdAt,
  authorId: MOCK_PROFILE.id,
  permalink: `https://x.com/${MOCK_PROFILE.username}/status/${post.id}`,
  hashtags: post.hashtags,
  mentions: post.mentions,
  metrics: {
    likeCount: post.likes,
    repostCount: post.reposts,
    replyCount: post.replies,
    viewCount: post.views,
  },
  media: post.media
    ? [
        {
          mediaKey: `media-${post.id}`,
          type: 'photo',
          url: post.media,
        },
      ]
    : [],
});
